<a href="https://colab.research.google.com/github/biswal-prem-5677/Coding-Journey/blob/main/python/libraries/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/Social_Network_Ads[1].csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [ ]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [ ]:
print(df.shape)
#**shape:** Returns dimensions of the DataFrame.

(400, 5)

In [ ]:
print(df.size)
#**size:** gives the total number of elements in the DataFrame

2000

In [ ]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
df.iloc[4:7]

    User ID  Gender  Age  EstimatedSalary  Purchased
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0

In [ ]:
df.loc[4:7, : ]

    User ID  Gender  Age  EstimatedSalary  Purchased
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1

In [ ]:
d=df.drop(3,axis=0)
d

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[399 rows x 5 columns]

In [ ]:
df['Age'].unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54])

In [ ]:
df['User ID'].unique()

array([15624510, 15810944, 15668575, 15603246, 15804002, 15728773,
       15598044, 15694829, 15600575, 15727311, 15570769, 15606274,
       15746139, 15704987, 15628972, 15697686, 15733883, 15617482,
       15704583, 15621083, 15649487, 15736760, 15714658, 15599081,
       15705113, 15631159, 15792818, 15633531, 15744529, 15669656,
       15581198, 15729054, 15573452, 15776733, 15724858, 15713144,
       15690188, 15689425, 15671766, 15782806, 15764419, 15591915,
       15772798, 15792008, 15715541, 15639277, 15798850, 15776348,
       15727696, 15793813, 15694395, 15764195, 15744919, 15671655,
       15654901, 15649136, 15775562, 15807481, 15642885, 15789109,
       15814004, 15673619, 15595135, 15583681, 15605000, 15718071,
       15679760, 15654574, 15577178, 15595324, 15756932, 15726358,
       15595228, 15782530, 15592877, 15651983, 15746737, 15774179,
       15667265, 15655123, 15595917, 15668385, 15709476, 15711218,
       15798659, 15663939, 15694946, 15631912, 15768816, 15682268,
       15684801, 15636428, 15809823, 15699284, 15786993, 15709441,
       15710257, 15582492, 15575694, 15756820, 15766289, 15593014,
       15584545, 15675949, 15672091, 15801658, 15706185, 15789863,
       15720943, 15697997, 15665416, 15660200, 15619653, 15773447,
       15739160, 15689237, 15679297, 15591433, 15642725, 15701962,
       15811613, 15741049, 15724423, 15574305, 15678168, 15697020,
       15610801, 15745232, 15722758, 15792102, 15675185, 15801247,
       15725660, 15638963, 15800061, 15578006, 15668504, 15687491,
       15610403, 15741094, 15807909, 15666141, 15617134, 15783029,
       15622833, 15746422, 15750839, 15749130, 15779862, 15767871,
       15679651, 15576219, 15699247, 15619087, 15605327, 15610140,
       15791174, 15602373, 15762605, 15598840, 15744279, 15670619,
       15599533, 15757837, 15697574, 15578738, 15762228, 15614827,
       15789815, 15579781, 15587013, 15570932, 15794661, 15581654,
       15644296, 15614420, 15609653, 15594577, 15584114, 15673367,
       15685576, 15774727, 15694288, 15603319, 15759066, 15814816,
       15724402, 15571059, 15674206, 15715160, 15730448, 15662067,
       15779581, 15662901, 15689751, 15667742, 15738448, 15680243,
       15745083, 15708228, 15628523, 15708196, 15735549, 15809347,
       15660866, 15766609, 15654230, 15794566, 15800890, 15697424,
       15724536, 15735878, 15707596, 15657163, 15622478, 15779529,
       15636023, 15582066, 15666675, 15732987, 15789432, 15663161,
       15694879, 15593715, 15575002, 15622171, 15795224, 15685346,
       15691808, 15721007, 15794253, 15694453, 15813113, 15614187,
       15619407, 15646227, 15660541, 15753874, 15617877, 15772073,
       15701537, 15736228, 15780572, 15769596, 15586996, 15722061,
       15638003, 15775590, 15730688, 15753102, 15810075, 15723373,
       15795298, 15584320, 15724161, 15750056, 15609637, 15794493,
       15569641, 15815236, 15811177, 15680587, 15672821, 15767681,
       15600379, 15801336, 15721592, 15581282, 15746203, 15583137,
       15680752, 15688172, 15791373, 15589449, 15692819, 15727467,
       15734312, 15764604, 15613014, 15759684, 15609669, 15685536,
       15750447, 15663249, 15638646, 15734161, 15631070, 15761950,
       15649668, 15713912, 15586757, 15596522, 15625395, 15760570,
       15566689, 15725794, 15673539, 15705298, 15675791, 15747043,
       15736397, 15678201, 15720745, 15637593, 15598070, 15787550,
       15603942, 15733973, 15596761, 15652400, 15717893, 15622585,
       15733964, 15753861, 15747097, 15594762, 15667417, 15684861,
       15742204, 15623502, 15774872, 15611191, 15674331, 15619465,
       15575247, 15695679, 15713463, 15785170, 15796351, 15639576,
       15693264, 15589715, 15769902, 15587177, 15814553, 15601550,
       15664907, 15612465, 15810800, 15665760, 15588080, 15776844,
       15717560, 15629739, 15729908, 15716781, 15646936, 15768151,
       15579212, 15721835, 15800515, 15591279, 15587419, 15750335,
       15699619, 15606472, 15778368, 15671387, 15573926, 15709183,
       15577514, 15778830, 15768072, 15768293, 15654456, 15807525,
       15574372, 15671249, 15779744, 15624755, 15611430, 15774744,
       15629885, 15708791, 15793890, 15646091, 15596984, 15800215,
       15577806, 15749381, 15683758, 15670615, 15715622, 15707634,
       15806901, 15775335, 15724150, 15627220, 15672330, 15668521,
       15807837, 15592570, 15748589, 15635893, 15757632, 15691863,
       15706071, 15654296, 15755018, 15594041])

In [ ]:
#**iloc[]:** Integer-location based indexing.
print(df.iloc[0:2,  :])

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [ ]:
df.loc[9]
#**loc[]:** Label-based indexing.

User ID            15727311
Gender               Female
Age                      35
EstimatedSalary       65000
Purchased                 0
Name: 9, dtype: object

In [ ]:
df.loc[99]

User ID            15756820
Gender               Female
Age                      28
EstimatedSalary       37000
Purchased                 0
Name: 99, dtype: object

In [ ]:
# single column
df[['User ID']]

#extract a particular column from a DataFrame

      User ID
0    15624510
1    15810944
2    15668575
3    15603246
4    15804002
..        ...
395  15691863
396  15706071
397  15654296
398  15755018
399  15594041

[400 rows x 1 columns]

In [ ]:
df[['Purchased']]
#extract a particular column from a DataFrame

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [ ]:
## multiple column
df[['User ID', 'Purchased',"Age"]]

      User ID  Purchased  Age
0    15624510          0   19
1    15810944          0   35
2    15668575          0   26
3    15603246          0   27
4    15804002          0   19
..        ...        ...  ...
395  15691863          1   46
396  15706071          1   51
397  15654296          1   50
398  15755018          0   36
399  15594041          1   49

[400 rows x 3 columns]

In [ ]:
df['Age'].value_counts()
#**value_counts():** Count unique values in a Series.

Age
35    32
37    20
26    16
41    16
42    16
39    15
40    15
48    14
47    14
27    13
38    13
28    12
36    12
46    12
31    11
30    11
49    10
29    10
33     9
32     9
24     9
59     7
19     7
45     7
20     7
60     7
34     6
23     6
52     6
25     6
58     6
53     5
57     5
22     5
18     5
21     4
50     4
54     4
55     3
56     3
51     3
43     3
44     2
Name: count, dtype: int64

In [ ]:
#**max() and min():** Find the maximum and minimum values in each column.

print(df.max())

User ID            15815236
Gender                 Male
Age                      60
EstimatedSalary      150000
Purchased                 1
dtype: object

In [ ]:
print(df.min())

User ID            15566689
Gender               Female
Age                      18
EstimatedSalary       15000
Purchased                 0
dtype: object

In [ ]:
df['x1'] = df['EstimatedSalary'] % 2
df

      User ID  Gender  Age  EstimatedSalary  Purchased  x1
0    15624510    Male   19            19000          0   0
1    15810944    Male   35            20000          0   0
2    15668575  Female   26            43000          0   0
3    15603246  Female   27            57000          0   0
4    15804002    Male   19            76000          0   0
..        ...     ...  ...              ...        ...  ..
395  15691863  Female   46            41000          1   0
396  15706071    Male   51            23000          1   0
397  15654296  Female   50            20000          1   0
398  15755018    Male   36            33000          0   0
399  15594041  Female   49            36000          1   0

[400 rows x 6 columns]

In [ ]:
df_new = df.drop('Age',axis=1)
df

      User ID  Gender  Age  EstimatedSalary  Purchased  x1
0    15624510    Male   19            19000          0   0
1    15810944    Male   35            20000          0   0
2    15668575  Female   26            43000          0   0
3    15603246  Female   27            57000          0   0
4    15804002    Male   19            76000          0   0
..        ...     ...  ...              ...        ...  ..
395  15691863  Female   46            41000          1   0
396  15706071    Male   51            23000          1   0
397  15654296  Female   50            20000          1   0
398  15755018    Male   36            33000          0   0
399  15594041  Female   49            36000          1   0

[400 rows x 6 columns]