<a href="https://colab.research.google.com/github/biswal-prem-5677/Coding-Journey/blob/main/pndas/libraries/Pandas_A_to_Z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
ser1 = pd.Series(["IND","AUS","NZ","ENG","SA","WI"])
print(ser1)

0    IND
1    AUS
2     NZ
3    ENG
4     SA
5     WI
dtype: object

In [ ]:
import pandas as pd
import numpy as np
a=["IND:","AUS:","ENG:"]
b=["New Delhi","Sidney","London"]

ser1=pd.Series(b,index=a)
print(ser1)

IND:    New Delhi
AUS:       Sidney
ENG:       London
dtype: object

In [ ]:
import pandas as pd
ser1 = pd.Series([1.5, 2.5, 3, 4.5, 5.0, 6])
print(ser1)

0    1.5
1    2.5
2    3.0
3    4.5
4    5.0
5    6.0
dtype: float64

In [ ]:
import pandas as pd
ser2 = pd.Series(["India", "Canada", "Germany"], name="Countries")
print(ser2)

0      India
1     Canada
2    Germany
Name: Countries, dtype: object

In [ ]:
import pandas as pd
ser4 = pd.Series({"India": "New Delhi",
"Japan": "Tokyo",
"UK": "London"})
print(ser4)

India    New Delhi
Japan        Tokyo
UK          London
dtype: object

In [ ]:
import pandas as pd
import numpy as np
ser1 = pd.Series({"India": "New Delhi",
"Japan": "Tokyo",
"UK": "London"})
print(ser1.values)
print(ser1.index)

['New Delhi' 'Tokyo' 'London']
Index(['India', 'Japan', 'UK'], dtype='object')

In [ ]:
import pandas as pd
values = ["India", "Canada", "Australia",
"Japan", "Germany", "France"]
code = ["IND", "CAN", "AUS", "JAP", "GER", "FRA"]
ser1 = pd.Series(values, index=code)
print(ser1)

IND        India
CAN       Canada
AUS    Australia
JAP        Japan
GER      Germany
FRA       France
dtype: object

In [ ]:
import pandas as pd
values = ["India", "Canada", "Australia",
"Japan", "Germany", "France"]
code = ["IND", "CAN", "AUS", "JAP", "GER", "FRA"]
ser1 = pd.Series(values, index=code)
print(len(ser1))
print(ser1.shape)
print(ser1.size)

6
(6,)
6

In [ ]:
import pandas as pd
values = ["India", "Canada", "Australia",
"Japan", "Germany", "France"]
code = ["IND", "CAN", "AUS", "JAP", "GER", "FRA"]
ser1 = pd.Series(values, index=code)
print(ser1)

IND        India
CAN       Canada
AUS    Australia
JAP        Japan
GER      Germany
FRA       France
dtype: object

In [ ]:
ser1.head()

IND        India
CAN       Canada
AUS    Australia
JAP        Japan
GER      Germany
dtype: object

In [ ]:
ser1.head(3)

IND        India
CAN       Canada
AUS    Australia
dtype: object

In [ ]:
ser1.tail()

CAN       Canada
AUS    Australia
JAP        Japan
GER      Germany
FRA       France
dtype: object

In [ ]:
ser1.tail(3)

JAP      Japan
GER    Germany
FRA     France
dtype: object

In [ ]:
ser1.take([2, 4, 5])

AUS    Australia
GER      Germany
FRA       France
dtype: object

In [ ]:
import pandas as pd

num =[000,100,200, 300, 400,500,600,700,800,900]
idx =['A','B','C', 'D','E','F', 'G','H','I','J']
series=pd.Series(num,index=idx)
series

A      0
B    100
C    200
D    300
E    400
F    500
G    600
H    700
I    800
J    900
dtype: int64

In [ ]:
series[0:3]# Displaying 0th, 1st and 2nd Index

A      0
B    100
C    200
dtype: int64

In [ ]:
series[2:4]# Displaying 2nd and 3rd Index

C    200
D    300
dtype: int64

In [ ]:
series[1:6:2]# Displaying from 1st index(included) to 6th Index(Excluded) with an increment of 2

B    100
D    300
F    500
dtype: int64

In [ ]:
series[:6]

A      0
B    100
C    200
D    300
E    400
F    500
dtype: int64

In [ ]:
import pandas as pd
employees = pd.DataFrame({
'EmpCode': ['Emp001', 'Emp002', 'Emp003', 'Emp004', 'Emp005'],
'Name': ['John', 'Doe', 'William', 'Spark', 'Mark'],
'Occupation': ['Chemist', 'Statistician', 'Statistician',
'Statistician', 'Programmer'],
'Date Of Join': ['2018-01-25', '2018-01-26', '2018-01-26', '2018-02-26',
'2018-03-16'],
'Age': [23, 24, 34, 29, 40]})
print(employees)

  EmpCode     Name    Occupation Date Of Join  Age
0  Emp001     John       Chemist   2018-01-25   23
1  Emp002      Doe  Statistician   2018-01-26   24
2  Emp003  William  Statistician   2018-01-26   34
3  Emp004    Spark  Statistician   2018-02-26   29
4  Emp005     Mark    Programmer   2018-03-16   40

In [ ]:
import pandas as pd
employees1 = pd.DataFrame({
'EmpCode': ['Emp001', 'Emp002', 'Emp003', 'Emp004', 'Emp005'],
'Name': ['John', 'Doe', 'William', 'Spark', 'Mark'],
'Occupation': ['Chemist', 'Statistician', 'Statistician',
'Statistician', 'Programmer'],
'Date Of Join': ['2018-01-25', '2018-01-26', '2018-01-26', '2018-02-26',
'2018-03-16'],
'Age': [23, 24, 34, 29, 40]},
index=['Emp001', 'Emp002','Emp003', 'Emp004', 'Emp005'],
columns=['Name', 'Occupation', 'Date Of Join', 'Age'])
print(employees1)

           Name    Occupation Date Of Join  Age
Emp001     John       Chemist   2018-01-25   23
Emp002      Doe  Statistician   2018-01-26   24
Emp003  William  Statistician   2018-01-26   34
Emp004    Spark  Statistician   2018-02-26   29
Emp005     Mark    Programmer   2018-03-16   40

In [ ]:
employees=pd.DataFrame({
'EmpCode':['Emp001','Emp002','Emp003','Emp004','Emp005'],
'Name':['John', 'Doe','William','Spark','Mark'],
'Occupation':['Chemist','Statistician','Statistician',
'Statistician','Programmer'],
'Date Of Join':['2018-01-25','2018-01-26','2018-01-26','2018-02-26',
'2018-03-16'],
'Age':[23,24,34,29,40]})
print(employees)

  EmpCode     Name    Occupation Date Of Join  Age
0  Emp001     John       Chemist   2018-01-25   23
1  Emp002      Doe  Statistician   2018-01-26   24
2  Emp003  William  Statistician   2018-01-26   34
3  Emp004    Spark  Statistician   2018-02-26   29
4  Emp005     Mark    Programmer   2018-03-16   40

In [ ]:
employees.columns=['EmpCode','EmpName','EmpOccupation','EmpDOJ', 'EmpAge']
print(employees)

  EmpCode  EmpName EmpOccupation      EmpDOJ  EmpAge
0  Emp001     John       Chemist  2018-01-25      23
1  Emp002      Doe  Statistician  2018-01-26      24
2  Emp003  William  Statistician  2018-01-26      34
3  Emp004    Spark  Statistician  2018-02-26      29
4  Emp005     Mark    Programmer  2018-03-16      40

In [ ]:
employees=pd.DataFrame({
'EmpCode':['Emp001','Emp002','Emp003','Emp004','Emp005'],
'Name':['John', 'Doe','William','Spark','Mark'],
'Occupation':['Chemist','Statistician','Statistician',
'Statistician','Programmer'],
'Date Of Join':['2018-01-25','2018-01-26','2018-01-26','2018-02-26',
'2018-03-16'],
'Age':[23,24,34,29,40]})

employees.drop('Age', axis=1,inplace=True)
print(employees)

  EmpCode     Name    Occupation Date Of Join
0  Emp001     John       Chemist   2018-01-25
1  Emp002      Doe  Statistician   2018-01-26
2  Emp003  William  Statistician   2018-01-26
3  Emp004    Spark  Statistician   2018-02-26
4  Emp005     Mark    Programmer   2018-03-16

In [ ]:
employees['City'] = ['London', 'Tokyo', 'Sydney', 'London', 'Toronto']
print(employees)

  EmpCode     Name    Occupation Date Of Join     City
0  Emp001     John       Chemist   2018-01-25   London
1  Emp002      Doe  Statistician   2018-01-26    Tokyo
2  Emp003  William  Statistician   2018-01-26   Sydney
3  Emp004    Spark  Statistician   2018-02-26   London
4  Emp005     Mark    Programmer   2018-03-16  Toronto

In [ ]:
print(list(employees))

['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'City']

In [ ]:
print(employees.columns.tolist())

['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'City']

In [ ]:
print(list(employees.columns.values))

['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'City']

In [ ]:
import pandas as pd
import numpy as np
df_random=pd.DataFrame(np.random.randint(100,size=(10,6)),columns=list('ABCDEF'),index=['Row-{}'.format(i) for i in range(10)])

print(df_random)

        A   B   C   D   E   F
Row-0  45   7   4  62  29  49
Row-1  83  75  24  94  87  47
Row-2  77  27  77  61  90   1
Row-3  38  17  65  70  21   6
Row-4  73  71  25  49  77  71
Row-5  89  42   7  43  97  29
Row-6  23  32  15  70  14  54
Row-7  37  69  30  12  38  98
Row-8  50   0  21  67  52  98
Row-9  70  94  77  83  52  72

In [ ]:

employees=pd.DataFrame({
'EmpCode':['Emp001','Emp002','Emp003','Emp004','Emp005'],
'Name':['John', 'Doe','William','Spark','Mark'],
'Occupation':['Chemist','Statistician','Statistician',
'Statistician','Programmer'],
'Date Of Join':['2018-01-25','2018-01-26','2018-01-26','2018-02-26',
'2018-03-16'],
'Age':[23,24,34,29,40]})
print(employees)
df = employees[['EmpCode', 'Age', 'Name']]
print(df)

  EmpCode     Name    Occupation Date Of Join  Age
0  Emp001     John       Chemist   2018-01-25   23
1  Emp002      Doe  Statistician   2018-01-26   24
2  Emp003  William  Statistician   2018-01-26   34
3  Emp004    Spark  Statistician   2018-02-26   29
4  Emp005     Mark    Programmer   2018-03-16   40
  EmpCode  Age     Name
0  Emp001   23     John
1  Emp002   24      Doe
2  Emp003   34  William
3  Emp004   29    Spark
4  Emp005   40     Mark

In [ ]:
df = pd.DataFrame()
if df.empty:
  print('DataFrame is empty!')

DataFrame is empty!

In [ ]:
import datetime
import pandas as pd

todays_date=datetime.datetime.now().date()
index=pd.date_range(todays_date,periods=10,freq='D')
columns=['A','B', 'C']

df= pd.DataFrame(index=index,columns=columns)
df= df.fillna(0)
print(df)

            A  B  C
2026-01-15  0  0  0
2026-01-16  0  0  0
2026-01-17  0  0  0
2026-01-18  0  0  0
2026-01-19  0  0  0
2026-01-20  0  0  0
2026-01-21  0  0  0
2026-01-22  0  0  0
2026-01-23  0  0  0
2026-01-24  0  0  0

/tmp/ipython-input-1621289434.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df= df.fillna(0)

In [ ]:
df= pd.DataFrame({'Age':[30,20,22,40,32,28,39],
'Color':['Blue', 'Green','Red', 'White','Gray', 'Black',
'Red'],
'Food':['Steak', 'Lamb','Mango', 'Apple','Cheese',
'Melon', 'Beans'],
'Height':[165,70,120,80,180, 172,150],
'Score':[4.6,8.3,9.0,3.3,1.8,9.5,2.2],
'State':['NY','TX','FL','AL', 'AK','TX','TX']
},
index=['Jane','Nick','Aaron','Penelope','Dean',
'Christina', 'Cornelia'])

print( df.dtypes)

Age         int64
Color      object
Food       object
Height      int64
Score     float64
State      object
dtype: object

In [ ]:
import pandas as pd
std_dtls = pd.DataFrame({
"std_name":["aaa","sss","ddd","fff","ggg"],"regd_no":[111,222,333,444,555],
"branch":["cse","ece","aero","mtech","bpharma"]})
print(std_dtls)
print(std_dtls.dtypes)
print(std_dtls.T)
print(std_dtls.loc[[3,1]])

med_rec ={
"pt_id":[111,222,333,444,555],
"pt_name":["aaa","bbb","ccc","fff","ooo"],
"age":[11,12,13,14,15],
"gender":["m","f","m","m","m"]}
med_dtls = pd.DataFrame(med_rec)
print(med_dtls)
med_dtls =pd.DataFrame(med_rec).set_index('pt_id')
print(med_dtls)
med_dtls = pd.DataFrame(med_rec).set_index('pt_name')
print(med_dtls)
med_dtls = pd.DataFrame(med_rec, index = ([11,12,13,16,18]))
print(med_dtls)

import numpy as np
pt_dtls={"pt_name": ["aaa","sss","ddd","fff","ggg"],"pt_id":[111,222,444,555,4444],"age":[23,24,25,26,27]}
index_array = ([101,102,103,104,105])
index_array = np.arange(1,6)
pt_record = pd.DataFrame(pt_dtls, index = index_array)
print(pt_record)
pt_record.index.name = "patient_sl_no"
print(pt_record)
#.loc[]
# label based indexing and slicing
print(pt_record.loc[3,"pt_name"])
print(pt_record.loc[3:5])
print(pt_record.loc[(pt_record.age>50) & (pt_record.age<60)])
#iloc
print(pt_record.iloc[1,2])

  std_name  regd_no   branch
0      aaa      111      cse
1      sss      222      ece
2      ddd      333     aero
3      fff      444    mtech
4      ggg      555  bpharma
std_name    object
regd_no      int64
branch      object
dtype: object
            0    1     2      3        4
std_name  aaa  sss   ddd    fff      ggg
regd_no   111  222   333    444      555
branch    cse  ece  aero  mtech  bpharma
  std_name  regd_no branch
3      fff      444  mtech
1      sss      222    ece
   pt_id pt_name  age gender
0    111     aaa   11      m
1    222     bbb   12      f
2    333     ccc   13      m
3    444     fff   14      m
4    555     ooo   15      m
      pt_name  age gender
pt_id
111       aaa   11      m
222       bbb   12      f
333       ccc   13      m
444       fff   14      m
555       ooo   15      m
         pt_id  age gender
pt_name
aaa        111   11      m
bbb        222   12      f
ccc        333   13      m
fff        444   14      m
ooo        555   15      m
    pt_id pt_name  age gender
11    111     aaa   11      m
12    222     bbb   12      f
13    333     ccc   13      m
16    444     fff   14      m
18    555     ooo   15      m
  pt_name  pt_id  age
1     aaa    111   23
2     sss    222   24
3     ddd    444   25
4     fff    555   26
5     ggg   4444   27
              pt_name  pt_id  age
patient_sl_no
1                 aaa    111   23
2                 sss    222   24
3                 ddd    444   25
4                 fff    555   26
5                 ggg   4444   27
ddd
              pt_name  pt_id  age
patient_sl_no
3                 ddd    444   25
4                 fff    555   26
5                 ggg   4444   27
Empty DataFrame
Columns: [pt_name, pt_id, age]
Index: []
24

In [ ]:
df1 =pd.DataFrame({'Age':[30,20,22,40],'Height':[165,70,120, 80],
'Score':[4.6,8.3,9.0,3.3],'State':['NY','TX',
'FL','AL']},
index=['Jane','Nick','Aaron','Penelope'])
print(df1)

df2 =pd.DataFrame({'Age':[32,28,39],'Color':['Gray','Black','Red'],
'Food':['Cheese','Melon','Beans'],
'Score':[1.8,9.5,2.2],'State':['AK','TX','TX']},
index=['Dean','Christina','Cornelia'])
print(df2)

df3 = pd.concat([df1, df2], sort=True)
print(df3)

          Age  Height  Score State
Jane       30     165    4.6    NY
Nick       20      70    8.3    TX
Aaron      22     120    9.0    FL
Penelope   40      80    3.3    AL
           Age  Color    Food  Score State
Dean        32   Gray  Cheese    1.8    AK
Christina   28  Black   Melon    9.5    TX
Cornelia    39    Red   Beans    2.2    TX
           Age  Color    Food  Height  Score State
Jane        30    NaN     NaN   165.0    4.6    NY
Nick        20    NaN     NaN    70.0    8.3    TX
Aaron       22    NaN     NaN   120.0    9.0    FL
Penelope    40    NaN     NaN    80.0    3.3    AL
Dean        32   Gray  Cheese     NaN    1.8    AK
Christina   28  Black   Melon     NaN    9.5    TX
Cornelia    39    Red   Beans     NaN    2.2    TX

In [ ]:
employees1 = pd.DataFrame({
'EmpCode': ['Emp001', 'Emp002', 'Emp003', 'Emp004', 'Emp005'],
'Name': ['John', 'Doe', 'William', 'Spark', 'Mark'],
'Occupation': ['Chemist', 'Statistician', 'Statistician',
'Statistician', 'Programmer'],
'Date Of Join': ['2018-01-25', '2018-01-26', '2018-01-26', '2018-02-26',
'2018-03-16'],
'Age': [23, 24, 34, 29, 40]},
index=['Emp001', 'Emp002','Emp003', 'Emp004', 'Emp005'],
columns=['Name', 'Occupation', 'Date Of Join', 'Age'])
print(employees1)

employees1.loc['Emp003'] = ['Bibhab', 'Programmer', '2018-01-25', 25]
print(employees1)

           Name    Occupation Date Of Join  Age
Emp001     John       Chemist   2018-01-25   23
Emp002      Doe  Statistician   2018-01-26   24
Emp003  William  Statistician   2018-01-26   34
Emp004    Spark  Statistician   2018-02-26   29
Emp005     Mark    Programmer   2018-03-16   40
          Name    Occupation Date Of Join  Age
Emp001    John       Chemist   2018-01-25   23
Emp002     Doe  Statistician   2018-01-26   24
Emp003  Bibhab    Programmer   2018-01-25   25
Emp004   Spark  Statistician   2018-02-26   29
Emp005    Mark    Programmer   2018-03-16   40

In [ ]:
a = {'A': 10, 'B': 20}
b = {'B': 30, 'C': 40, 'D': 50}
df1 = pd.DataFrame(a, index=[0])
df2 = pd.DataFrame(b, index=[1])

# Corrected usage for d1 using pd.concat instead of the removed .append()
d1 = pd.concat([df1, df2]).fillna(0)
print(d1)

d2= pd.concat([df1, df2]).fillna(0)
print(d2)

d3= pd.DataFrame()
d3= d3.combine_first(df1).combine_first(df2).fillna(0)
print(d3)

      A   B     C     D
0  10.0  20   0.0   0.0
1   0.0  30  40.0  50.0
      A   B     C     D
0  10.0  20   0.0   0.0
1   0.0  30  40.0  50.0
      A   B     C     D
0  10.0  20   0.0   0.0
1   0.0  30  40.0  50.0

In [ ]:
a = {'A': 10, 'B': 20}
b = {'B': 30, 'C': 40, 'D': 50}
df1 = pd.DataFrame(a, index=[0])
df2 = pd.DataFrame(b, index=[1])

d1= pd.DataFrame()
#d1= d1.append(df1)
#d1= d1.append(df2).fillna(0)
print(d1)

d2= pd.concat([df1, df2]).fillna(0)
print(d2)

d3= pd.DataFrame()
d3= d3.combine_first(df1).combine_first(df2).fillna(3)
print(d3)

Empty DataFrame
Columns: []
Index: []
      A   B     C     D
0  10.0  20   0.0   0.0
1   0.0  30  40.0  50.0
      A   B     C     D
0  10.0  20   3.0   3.0
1   3.0  30  40.0  50.0

In [ ]:
df= pd.DataFrame({'DateOfBirth':['1986-11-11','1999-05-12','1976-01-01',
'1986-06-01','1983-06-04','1990-03-07',
'1999-07-09'],
'State':['NY','TX','FL','AL', 'AK','TX','TX']
},
index=['Jane','Pane','Aaron','Penelope','Frane',
'Christina', 'Cornelia'])

df1 =df[df.index.str.contains('ane') &df['State'].str.contains("TX")]
print(df1)

df2 =df[df.index.str.contains('ane') |df['State'].str.contains("TX")]
print(df2)

     DateOfBirth State
Pane  1999-05-12    TX
          DateOfBirth State
Jane       1986-11-11    NY
Pane       1999-05-12    TX
Frane      1983-06-04    AK
Christina  1990-03-07    TX
Cornelia   1999-07-09    TX

In [ ]:
df= pd.DataFrame({'State':['NY','TX','FL','AL', 'AK','TX','TX']
},
index=['Jane','Nick','Aaron','Penelope','Dean',
'Christina', 'Cornelia'])

print(df["State"].unique())

['NY' 'TX' 'FL' 'AL' 'AK']

In [ ]:
df= pd.DataFrame({'Age':[30,20,22,40,20,30,20,25],
'Height':[165,70,120,80,162, 72,124,81],
'Score':[4.6,8.3,9.0,3.3,4, 8,9,3],
'State':['NY','TX','FL','AL', 'NY','TX','FL','AL']},
index=['Jane','Nick','Aaron','Penelope','Jaane','Nicky','Armour','Ponting'])


print(df.Age.value_counts())

Age
20    3
30    2
22    1
40    1
25    1
Name: count, dtype: int64

In [ ]:
df= pd.DataFrame({'Age':[30,30,22,40,20,30,20,25],
'Height':[165,165,120,80,162, 72,124,81],
'Score':[4.6,4.6,9.0,3.3,4,8,9,3],
'State':['NY','NY','FL','AL', 'NY','TX','FL', 'AL']},
index=['Jane','Jane','Aaron','Penelope','Jaane', 'Nicky',
'Armour','Ponting'])

df1 =df.reset_index().drop_duplicates(subset='index',
keep='first').set_index('index')
print(df1)

          Age  Height  Score State
index
Jane       30     165    4.6    NY
Aaron      22     120    9.0    FL
Penelope   40      80    3.3    AL
Jaane      20     162    4.0    NY
Nicky      30      72    8.0    TX
Armour     20     124    9.0    FL
Ponting    25      81    3.0    AL

In [ ]:
df= pd.DataFrame([[10,20,30,40],[7,14,21,28], [5,]],
columns=['Apple','Orange','Banana','Pear'],
index=['Basket1','Basket2','Basket3'])

print(df.isnull())

print(df.notnull())

         Apple  Orange  Banana   Pear
Basket1  False   False   False  False
Basket2  False   False   False  False
Basket3  False    True    True   True
         Apple  Orange  Banana   Pear
Basket1   True    True    True   True
Basket2   True    True    True   True
Basket3   True   False   False  False

In [ ]:
df= pd.DataFrame([[10,20,30,40],[7,14,21,28], [5,]],
columns=['Apple','Orange','Banana','Pear'],
index=['Basket1','Basket2','Basket3'])

df.dropna()

         Apple  Orange  Banana  Pear
Basket1     10    20.0    30.0  40.0
Basket2      7    14.0    21.0  28.0

In [ ]:
df= pd.DataFrame([[10,20,30,40],[7,14,21,28], [5,]],
columns=['Apple','Orange','Banana','Pear'],
index=['Basket1','Basket2','Basket3'])
df.dropna(axis=1)

         Apple
Basket1     10
Basket2      7
Basket3      5

In [70]:
df= pd.read_csv(r"/content/drive/MyDrive/TMDB_all_movies.csv")
df.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.100,353.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,suomi,"Marja Packalén, Olli Varja, Matti Pellonpää, J...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9326.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.291,413.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,"suomi, English, svenska","Riikka Kuosmanen, Bertta Pellonpää, Aki Kauris...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.4,8158.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.869,2709.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Paul Skemp, Sammi Davis, Quinn Hellerman, Davi...","Robert Rodriguez, Allison Anders, Quentin Tara...","Andrzej Sekula, Rodrigo García, Guillermo Nava...","Robert Rodriguez, Allison Anders, Quentin Tara...","Lawrence Bender, Quentin Tarantino, Alexandre ...",Combustible Edison,6.7,114868.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,354.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Michael Wiseman, Michael DeLorenzo, Everlast, ...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Marilyn Vance, Lloyd Segan",Alan Silvestri,6.6,20255.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.500,27.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Michael Glawogger, Timo Novotny","Ulrich Gehmacher, Timo Novotny",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg

In [71]:
pd.read_csv(r"/content/drive/MyDrive/TMDB_all_movies.csv")

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.100,353.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,suomi,"Marja Packalén, Olli Varja, Matti Pellonpää, J...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9326.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.291,413.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,"suomi, English, svenska","Riikka Kuosmanen, Bertta Pellonpää, Aki Kauris...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.4,8158.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.869,2709.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Paul Skemp, Sammi Davis, Quinn Hellerman, Davi...","Robert Rodriguez, Allison Anders, Quentin Tara...","Andrzej Sekula, Rodrigo García, Guillermo Nava...","Robert Rodriguez, Allison Anders, Quentin Tara...","Lawrence Bender, Quentin Tarantino, Alexandre ...",Combustible Edison,6.7,114868.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,354.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Michael Wiseman, Michael DeLorenzo, Everlast, ...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Marilyn Vance, Lloyd Segan",Alan Silvestri,6.6,20255.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.500,27.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Michael Glawogger, Timo Novotny","Ulrich Gehmacher, Timo Novotny",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093041,1531399,What's Cookin?,0.000,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093042,1531400,Miley Cyrus: Jingle Bell Ball 2013,0.000,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093043,1531401,Quello che...,0.000,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093044,1531402,Service Charge,0.000,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093045,1531403,Selena Gomez: Jingle Bell Ball 2013,0.000,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
url ="https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv"

df1 =pd.read_csv(url)
df1.head()

         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0          0       0
1  2020-01-23  Afghanistan          0          0       0
2  2020-01-24  Afghanistan          0          0       0
3  2020-01-25  Afghanistan          0          0       0
4  2020-01-26  Afghanistan          0          0       0

In [74]:
df.head(12)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.100,353.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,suomi,"Marja Packalén, Olli Varja, Matti Pellonpää, J...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9326.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.291,413.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,"suomi, English, svenska","Riikka Kuosmanen, Bertta Pellonpää, Aki Kauris...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.4,8158.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.869,2709.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Paul Skemp, Sammi Davis, Quinn Hellerman, Davi...","Robert Rodriguez, Allison Anders, Quentin Tara...","Andrzej Sekula, Rodrigo García, Guillermo Nava...","Robert Rodriguez, Allison Anders, Quentin Tara...","Lawrence Bender, Quentin Tarantino, Alexandre ...",Combustible Edison,6.7,114868.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,354.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Michael Wiseman, Michael DeLorenzo, Everlast, ...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Marilyn Vance, Lloyd Segan",Alan Silvestri,6.6,20255.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.500,27.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Michael Glawogger, Timo Novotny","Ulrich Gehmacher, Timo Novotny",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg
5,9,Sunday in August,6.800,28.0,Released,2004-09-02,0.0,15.0,0.0,tt0425473,...,Deutsch,"Rita Lengyel, Milton Welsh","Anna Haas, Marc Meyer",Peter Polsak-Lohmann,Marc Meyer,Marc Meyer,Christian Biegai,6.8,14.0,NaN
6,11,Star Wars,8.205,21388.0,Released,1977-05-25,775398007.0,121.0,11000000.0,tt0076759,...,English,"Robert Davies, Derek Lyons, Hal Wamsley, Laine...",George Lucas,Gilbert Taylor,George Lucas,"George Lucas, Gary Kurtz",John Williams,8.6,1526792.0,/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg
7,12,Finding Nemo,7.800,19797.0,Released,2003-05-30,940335536.0,100.0,94000000.0,tt0266543,...,English,"Geoff Brooks, Lisa Peers, Paul Eiding, Mickie ...",Andrew Stanton,"Sharon Calahan, Jeremy Lasky","Blake Tucker, Bob Peterson, Andrew Stanton, Da...","John Lasseter, Graham Walters",Thomas Newman,8.2,1172496.0,/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg
8,13,Forrest Gump,8.466,28511.0,Released,1994-06-23,677387716.0,142.0,55000000.0,tt0109830,...,English,"Logan Livingston Gomez, Bob Harks, Ben Waddel,...",Robert Zemeckis,Don Burgess,"Eric Roth, Winston Groom","Steve Tisch, Wendy Finerman, Steve Starkey",Alan Silvestri,8.8,2408818.0,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg
9,14,American Beauty,8.006,12489.0,Released,1999-09-15,356296601.0,122.0,15000000.0,tt0169547,...,English,"Wes Bentley, Chris Cooper, Peter Gallagher, Mo...",Sam Mendes,Conrad L. Hall,Alan Ball,"Dan Jinks, Bruce Cohen",Thomas Newman,8.3,1257493.0,/wby9315QzVKdW9BonAefg8jGTTb.jpg
10,15,Citizen Kane,8.000,5713.0,Released,1941-04-17,23218000.0,119.0,839727.0,tt0033467,...,English,"Ernest Grooney, George Sherwood, Tim Davis, Sa...",Orson Welles,Gregg Toland,"Herman J. Mankiewicz, Orson Welles",Orson Welles,Bernard Herrmann,8.3,485120.0,/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg
11,16,Dancer in the Dark,7.900,1883.0,Released,2000-09-01,40061153.0,140.0,12500000.0,tt0168629,...,English,"John Randolph Jones, David Morse, Karoliina He...",Lars von Trier,Robby Müller,"Sjón, Lars von Trier","Leo Pescarolo, Peter Aalbæk Jensen, Vibeke Win...",Björk,7.9,121520.0,/9rsivF4sWfmBzrNr4LPu6TNJhXX.jpg

In [75]:
df.tail()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
1093041,1531399,What's Cookin?,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093042,1531400,Miley Cyrus: Jingle Bell Ball 2013,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093043,1531401,Quello che...,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093044,1531402,Service Charge,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093045,1531403,Selena Gomez: Jingle Bell Ball 2013,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df.tail(3)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
1093043,1531401,Quello che...,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093044,1531402,Service Charge,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093045,1531403,Selena Gomez: Jingle Bell Ball 2013,0.0,0.0,Released,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093046 entries, 0 to 1093045
Data columns (total 28 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   id                       1093046 non-null  int64
 1   title                    1093034 non-null  object
 2   vote_average             1093046 non-null  float64
 3   vote_count               1093046 non-null  float64
 4   status                   1093046 non-null  object
 5   release_date             980399 non-null   object
 6   revenue                  1093046 non-null  float64
 7   runtime                  1093046 non-null  float64
 8   budget                   1093046 non-null  float64
 9   imdb_id                  626123 non-null   object
 10  original_language        1093046 non-null  object
 11  original_title           1093034 non-null  object
 12  overview                 921995 non-null   object
 13  popularity               1093046 non-null  float64
 14  tagline                  163920 non-null   object
 15  genres                   792036 non-null   object
 16  production_companies     519523 non-null   object
 17  production_countries     675643 non-null   object
 18  spoken_languages         688724 non-null   object
 19  cast                     742126 non-null   object
 20  director                 913248 non-null   object
 21  director_of_photography  281262 non-null   object
 22  writers                  545907 non-null   object
 23  producers                364099 non-null   object
 24  music_composer           117195 non-null   object
 25  imdb_rating              450436 non-null   float64
 26  imdb_votes               450436 non-null   float64
 27  poster_path              813787 non-null   object
dtypes: float64(8), int64(1), object(19)
memory usage: 233.5+ MB

In [78]:
df.dtypes

id                           int64
title                       object
vote_average               float64
vote_count                 float64
status                      object
release_date                object
revenue                    float64
runtime                    float64
budget                     float64
imdb_id                     object
original_language           object
original_title              object
overview                    object
popularity                 float64
tagline                     object
genres                      object
production_companies        object
production_countries        object
spoken_languages            object
cast                        object
director                    object
director_of_photography     object
writers                     object
producers                   object
music_composer              object
imdb_rating                float64
imdb_votes                 float64
poster_path                 object
dtype: object

In [79]:
df.describe()

,id,vote_average,vote_count,revenue,runtime,budget,popularity,imdb_rating,imdb_votes
count,1.093046e+06,1.093046e+06,1.093046e+06,1.093046e+06,1.093046e+06,1.093046e+06,1.093046e+06,450436.000000,4.504360e+05
mean,7.805643e+05,2.066852e+00,2.311003e+01,7.365501e+05,4.487504e+01,2.905472e+05,8.665819e-01,6.243252,2.789342e+03
std,4.367683e+05,3.077043e+00,3.653924e+02,1.727691e+07,5.582823e+01,4.795978e+06,2.751393e+00,1.322443,3.194960e+04
min,2.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,5.000000e+00
25%,4.097562e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.031000e-01,5.500000,2.000000e+01
50%,7.711065e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01,0.000000e+00,6.000000e-01,6.300000,5.900000e+01
75%,1.166280e+06,5.000000e+00,1.000000e+00,0.000000e+00,8.500000e+01,0.000000e+00,9.360000e-01,7.100000,2.620000e+02
max,1.531403e+06,1.000000e+01,3.778200e+04,2.923706e+09,1.440000e+04,6.000000e+08,1.396378e+03,10.000000,3.084069e+06

In [80]:
url = "https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv" # COVID data

df1 = pd.read_csv(url)
df1.shape

(161568, 5)

In [81]:
df.iloc[2:6]#Viewing Data from 2nd Index(included) to 6th Index(excluded)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
2,5,Four Rooms,5.869,2709.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,English,"Paul Skemp, Sammi Davis, Quinn Hellerman, Davi...","Robert Rodriguez, Allison Anders, Quentin Tara...","Andrzej Sekula, Rodrigo García, Guillermo Nava...","Robert Rodriguez, Allison Anders, Quentin Tara...","Lawrence Bender, Quentin Tarantino, Alexandre ...",Combustible Edison,6.7,114868.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,354.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,English,"Michael Wiseman, Michael DeLorenzo, Everlast, ...",Stephen Hopkins,Peter Levy,"Jere Cunningham, Lewis Colick","Gene Levy, Marilyn Vance, Lloyd Segan",Alan Silvestri,6.6,20255.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.500,27.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,"English, हिन्दी, 日本語, Pусский, Español",NaN,Timo Novotny,Wolfgang Thaler,"Michael Glawogger, Timo Novotny","Ulrich Gehmacher, Timo Novotny",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg
5,9,Sunday in August,6.800,28.0,Released,2004-09-02,0.0,15.0,0.0,tt0425473,...,Deutsch,"Rita Lengyel, Milton Welsh","Anna Haas, Marc Meyer",Peter Polsak-Lohmann,Marc Meyer,Marc Meyer,Christian Biegai,6.8,14.0,NaN

In [82]:
df.iloc[2:6,0:5]

   id                             title  vote_average  vote_count    status
2   5                        Four Rooms         5.869      2709.0  Released
3   6                    Judgment Night         6.500       354.0  Released
4   8  Life in Loops (A Megacities RMX)         7.500        27.0  Released
5   9                  Sunday in August         6.800        28.0  Released

In [83]:
df.spoken_languages.unique()

array(['suomi', 'suomi, English, svenska', 'English', ...,
       'English, ?????, , தமிழ்', 'English, Español, தமிழ்',
       'العربية, English, suomi, Bahasa melayu'], dtype=object)

In [84]:
df.columns=df.columns.str.replace('Y','Year ')
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path'],
      dtype='object')

In [85]:
df.mode()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path
0,2,Home,0.0,0.0,Released,2006-01-01,0.0,0.0,0.0,tt37660515,...,English,Mel Blanc,Dave Fleischer,Mikhail Druyan,William Shakespeare,"Auguste Lumière, Louis Lumière",Ilaiyaraaja,6.2,9.0,/sRs2R6qI9C3Liv3hWrQTdmoSqqp.jpg
1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093041,1531399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093042,1531400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093043,1531401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093044,1531402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093045,1531403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
df.median(numeric_only=True)

id              771106.5
vote_average         0.0
vote_count           0.0
revenue              0.0
runtime             23.0
budget               0.0
popularity           0.6
imdb_rating          6.3
imdb_votes          59.0
dtype: float64